[package]
name = "tensor"
version = "0.0.0"
edition = "2024"
authors = [
    "YdrMaster <ydrml@hotmail.com>",
    "Simon25772 <ssh.king@qq.com>",
]

[dependencies]
digit-layout = "0.3"
ndarray-layout = "0.2"
